### ISSUE TITLE
Supplementary Documentation? 

### ISSUE THREAD

**Issue by hfboyce** [ines/course-starter-python#21]
Hi @ines!
I work for the University of British Columbia and have been working on the the development of Data Science courses using your framework. Your documentation was super helpful, but I’ve accumulated some additional tips through my work, so I’m putting together a step-by-step guide for setup and customization. I currently have your repo forked and I’m wondering if you would welcome a pull request once my guide is ready? The guide would be used as supplement to the existing documentation.
Finally, I just want to thank you so much for making this available and open. It’s been so fun working with your framework and I have been enjoying all of it (even the troubleshooting!)!

**Comment by ines** [comment]
Hi @hfboyce! Sorry for only getting to this now (I think I missed the notification on this repo). 

So glad to hear you've found this project useful and thanks for your work on the additional documentation 🙏 If you want to submit a PR, that'd be amazing!
